apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: prometheus
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: metrics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alertmanager-pdb
  namespace: prometheus
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: alerting
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
