apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promtail

resources:
  - namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/component: log-collector
    includeSelectors: false

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.1
    releaseName: promtail
    namespace: promtail
    valuesFile: values.yaml
