apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

resources:
  - ../../base

commonLabels:
  environment: prod

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.24.1
    releaseName: tempo
    namespace: tempo
    valuesFile: values-prod.yaml
    additionalValuesFiles:
      - ../../base/values.yaml

