apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - ../../base

commonLabels:
  environment: qa

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 80.13.0
    releaseName: prometheus
    namespace: prometheus
    valuesFile: values-qa.yaml
    additionalValuesFiles:
      - ../../base/values.yaml

