apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - namespace.yaml
  - datasources-configmap.yaml
  - dashboards-configmap.yaml
  - networkpolicy.yaml

# Grafana Helm Chart
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.3
    releaseName: grafana
    namespace: grafana
    valuesFile: values.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/component: visualization

