apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry

resources:
  - ../../base

commonLabels:
  environment: prod

helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.142.2
    releaseName: otel-collector
    namespace: opentelemetry
    valuesFile: values-prod.yaml
    additionalValuesFiles:
      - ../../base/values.yaml

